export const WEATHER_DETAILS_PAGE_MAP_HEIGHT = 400;
export const WEATHER_DETAILS_PAGE_MAP_WIDTH = '100%';
export const WEATHER_DETAILS_PAGE_MAP_ZOOM_LEVEL = 12;

export const HOMEPAGE_MAP_ZOOM_LEVEL = 3;
export const HOMEPAGE_MAP_HEIGHT = 400;
export const HOMEPAGE_MAP_WIDTH = '100%';

export const MAIN_LOCATION_MAP_ICON_SIZE = 50;
export const NEARBY_LOCATION_MAP_ICON_SIZE = 30;
