export const WEATHER_DETAILS_PAGE_MAP_HEIGHT = 400;
export const WEATHER_DETAILS_PAGE_MAP_WIDTH = '100%';
export const WEATHER_DETAILS_PAGE_MAP_ZOOM_LEVEL = 12;

export const HOMEPAGE_MAP_ZOOM_LEVEL = 3;
export const HOMEPAGE_MAP_HEIGHT = 400;
export const HOMEPAGE_MAP_WIDTH = '100%';

export const MAIN_LOCATION_MAP_ICON_SIZE = 50;
export const NEARBY_LOCATION_MAP_ICON_SIZE = 30;

export const NEARBY_LOCATION_RADIUS = 100;
export const NEARBY_LOCATIONS_LIMIT = 10;
export const NEARBY_LOCATION_TYPE = 'CITY';

// Google Analytics Event IDs

export const GA_EVENT_NAVIGATED_ICONS_ID = 8;
export const GA_EVENT_NAVIGATED_CONTACT_US_ID = 9;
export const GA_EVENT_NAVIGATED_ABOUT_US_ID = 10;
export const GA_EVENT_NAVIGATED_PRIVACY_POLICY_ID = 11;
export const GA_EVENT_NAVIGATED_ARKA_MITRA_WEBSITE_ID = 12;
export const GA_EVENT_NAVIGATED_SEARCHED_WEATHER_USING_GEO_COORDINATES_ID = 1;
export const GA_EVENT_NAVIGATED_SEARCHED_WEATHER_USING_LOCATION_NAME_ID = 2;
export const GA_EVENT_NAVIGATED_EXECUTED_EXPANDED_MAP_SEARCH_ID = 3;

export const GA_EVENT_SEARCH_TYPE_NEARBY_LOCATION_SEARCH_ID = 4;
export const GA_EVENT_SEARCH_TYPE_LOCATION_SEARCH_USING_TYPEAHEAD_AUTOCOMPLETE_ID = 5;

export const GA_EVENT_INTERACTION_EXPAND_NAV_BAR_SEARCH_BOX_ID = 7;
export const GA_EVENT_INTERACTION_DISPLAY_HOURLY_WEATHER_MODAL_ID = 6;

// Main cookie consent name

export const COOKIE_CONSENT_NAME = 'cookie-consent-value';
